version: "3"

services:
  dbservice:
    container_name: dbservice
    image: postgres:15.2-alpine3.17
    restart: always
    hostname: dbservice
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0000"
      POSTGRES_DB: mydb
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    stdin_open: true

  front-service:
    container_name: front-service
    build:
      context: ./front
      dockerfile: Dockerfile.dev
      tags:
        - "nfr:1.0.0"
      platforms:
        - "linux/arm64"
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app/front
      - /app/front/node_modules
    stdin_open: true

  back-service:
    container_name: back-service
    build:
      context: ./back
      dockerfile: Dockerfile.dev
      tags:
        - "nbn:1.0.0"
      platforms:
        - "linux/arm64"
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      dbservice:
        condition: service_started
    volumes:
      - ./back:/app/back
      - /app/back/node_modules
