version: "3"

services:
  db-service:
    container_name: postgre-server
    image: postgres:15.2-alpine3.17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0000"
      POSTGRES_DB: mydb
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432

  front-service:
    container_name: react-server
    build:
      context: ./front
      dockerfile: Dockerfile.dev
      tags:
        - "react-server:1.0.0"
      platforms:
        - "linux/arm64"
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app/front
      - /app/front/node_modules
    stdin_open: true

  back-service:
    container_name: nestjs-server
    build:
      context: ./back
      dockerfile: Dockerfile.dev
      tags:
        - "nestjs-server:1.0.0"
      platforms:
        - "linux/arm64"
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - back/.env
    depends_on:
      db-service:
        condition: service_started
    volumes:
      - ./back:/app/back
      - /app/back/node_modules
